### ISSUE TITLE
[Feature Request] a way to provide a parser override

### ISSUE THREAD

**Issue by DRoet** [GrapesJS/mjml#113]
Hi,

Since `mjml4-in-browser` is only being used to compile the `mjml` -> `html`, I was wondering if there is a way to create an override to the current parse method, to allow users to compile the `mjml` on the server instead.

something like:
```js
const editor = grapesjs.init({
  fromElement: 1,
  container : '#gjs',
  plugins: ['grapesjs-mjml'],
  pluginsOpts: {
    'grapesjs-mjml': {
      parser: async function (mjml) {
        const res = await axios.post("/parser", {
          mjml: mjml
        })
        // this returns the html
        return res.data
      }
    }
  }
});
```

pros: 
- this way the `mjml4-in-browser` package could become an optional `peerDependency` and would probably shave off a lot of the bundle size.
- parsing mjml in the browser can be quite heavy, so this should be less stress on the browser
- no future problems with running `mjml` in the browser since it is a node.js package

cons:
- parsing delay since you are now depending on network requests, needs error handling.

I don't have any experience with the grapesjs internals so I was just wondering if building something like this is even possible, @artf thoughts?

**Comment by larsdecker** [comment]
I like the idea.  I will look at the code and check if we can provide an option for it.

**Comment by artf** [comment]
https://github.com/GrapesJS/mjml/pull/341
