### ISSUE TITLE
Selector-Error in the demo with Firefox

### ISSUE THREAD

**Issue by RyanFlm** [GrapesJS/mjml#173]
Hello,
I've found an error with Firefox while using the Grapes-Editor with this MJML-Plugin.
If I select an element there is an error in the console and I can not edit the selected Element nor change the device. This error isn't occurring with the Chrome-Browser.
Here attached is an image from the [Demo](https://grapesjs.com/demo-mjml.html) with the error.
Thanks to any advice :D

![image](https://user-images.githubusercontent.com/50547464/78559783-470e7e80-7815-11ea-83bd-d3be3a73b44a.png)

**Comment by gl-ll** [comment]
Hello,
I am facing the same issue while using grapesjs-mjml in Firefox v75.0. No problem with Chrome and Edge. 
Thanks

**Comment by artf** [comment]
Closing this as it doesn't seem to be an issue anymore
