### ISSUE TITLE
Invalid Id attribute on mjml image tag 

### ISSUE THREAD

**Issue by conklin** [GrapesJS/mjml#179]
When utilizing the asset manager to upload a new image, the asset manager attaches an id attribute to the mjml image tag. This id attribute causes an mjml validation error preventing the use of mjml strict validation in down stream applications.

Steps to reproduce:

- Navigate to https://grapesjs.com/demo-mjml.html
- Double click on the sciolino-paris-bw.jpg image opeing the asset manager
<img width="915" alt="Screen Shot 2020-04-24 at 10 17 38 AM" src="https://user-images.githubusercontent.com/7264437/80222535-fff5fb00-8614-11ea-86ed-5a41f683882b.png">

- choose an image of your choice replacing the Parisian photo
<img width="831" alt="Screen Shot 2020-04-24 at 10 21 57 AM" src="https://user-images.githubusercontent.com/7264437/80222899-84487e00-8615-11ea-93ae-bffe64b86cda.png">

- View code via the  </> icon and be alerted to a warning 
<p  align="center"   ><img width="325" alt="Screen Shot 2020-04-24 at 10 23 31 AM" src="https://user-images.githubusercontent.com/7264437/80223257-0c2e8800-8616-11ea-8b69-38d3d3cb4597.png"></p>

- infringing line of code
```       
<mj-column>
        <mj-image width="200px" src="//placehold.it/350x250/78c5d6/fff/image1.jpg" id="is2ee"/>
 </mj-column>
```

Open questions:
I have yet to dig into the asset manager code to identify a fix. is the id a critical  part of the asset manager functionality?

**Comment by conklin** [comment]
@artf I have not  had a chance to dig into this further. Perhaps you may have some initial guidance on this?

**Comment by DRoet** [comment]
This seems so happen as soon as you hit, view code, you don't even have to do anything. I'm pretty sure its the mjml parser adding these id's and I do remember seeing this in the past. I might look into this when I got more time

**Comment by ThomasPof** [comment]
It seems the issue is not only for images. I found another way to reproduce the same kind of issue : 

- go to https://grapesjs.com/demo-mjml.html
- refresh the page
- open the "view code" popup : you should see ids

You can find those ids inside the local storage element gjs-mjml-components.

I'm new on this project, I'll have a look on my side, but it's the beginning of my reflexion

**Comment by ThomasPof** [comment]
I can see the same behavior on the original grapes.js builder :
- clone and run the project
- add an image on the index.html file
- open the code viewer : no id
- double click on the image
- close the asset manager
- open the code viewer : an id is added to the <img> tag

**Comment by ThomasPof** [comment]
There is an option `opts.cleanId` inside `getHtml()` function you can configure to remove auto-generated ids.
I'm trying to add it in grapesjs-mjml, but so far it's not removing unwanted ids

**Comment by ThomasPof** [comment]
Ok I understand everything :
the file `grapesjs/src/code_manager/model/HtmlGenerator.js` is updated with the "clean-id" function on the master branch of grapes, but it's not released yet !

**Comment by ThomasPof** [comment]
https://github.com/artf/grapesjs/issues/3273

**Comment by ThomasPof** [comment]
- I tried with the newest grapesjs - 0.16.37 (added through npm directly from the repo url)
- I added the `cleanId: true` in `opts` object in grapesjs-mjml
- I can see that it goes inside the `cleanId` function, but I didn't figured it out why it's still not removing ids...

Working on it...

**Comment by ThomasPof** [comment]
Dirty fix : add regex to all editor.getHtml() function like that 

`editor.getHtml().replaceAll(new RegExp(/ id="([^"]+)"/g),'')`

it will remove all ids. Not clean, but works!

**Comment by gkustas** [comment]
I know this is an old thread, but the problem still exists for me. Is there a published fix? I am using editor.runCommand('mjml-get-code') to get the HTML, and this is where I get the error. What can I do as a workaround? Edit the storage components? storage HTML?

**Comment by vinhnxv** [comment]
> Dirty fix : add regex to all editor.getHtml() function like that
> 
> `editor.getHtml().replaceAll(new RegExp(/ id="([^"]+)"/g),'')`
> 
> it will remove all ids. Not clean, but works!

Thank you so much!
I have reprocessed it:
```
editor.on('component:update:src', component => {
                    if (component.is('mj-image')) {
                        let code = editor.getHtml();
                        let componentId = component.getId()
                        let replace = ` id="${componentId}"`;
                        let re = new RegExp(replace, 'g');
                        code = code.replaceAll(re, '')
                        editor.setComponents(code);
                    }

                    return component;
                });
``` 

I try to use `component.removeAttributes('id')`
or 
```
const attr = component.getAttributes();
delete attr.id;
component.setAttributes(attr);
```

but still can not remove component ID.
