### ISSUE TITLE
After drap and drop <mj-image /> 

### ISSUE THREAD

**Issue by ramkychowdary** [GrapesJS/mjml#188]
I am facing one of issue after drap and drop of <mj-image/> I want to insert padding-left="0px" padding-right="0px" padding-bottom="0px" padding-top="0px" by default as show in below. Can you please help me here.

<mj-image src="https://sample.com/inc/images/welcome_logo.png" **padding-left="0px" padding-right="0px" padding-bottom="0px" padding-top="0px"** width="100px" align="justify"/>

**Comment by DRoet** [comment]
Only way I can think of is using the BlockManager to re-add the block with your own preference:

```
const image = editor.BlockManager.get('mj-image')
const image.content = 'mj-image src="" padding-left etc...'
editor.BlockManager.remove('mj-image')
editor.BlockManager.add('mj-image', image)
```
