### ISSUE TITLE
Padding and background of mj-column cannot be configured / are ignored.

### ISSUE THREAD

**Issue by aki-ks** [GrapesJS/mjml#199]
MJML allows to specify padding and background-color for mj-columns but such options are not available in grapesjs-mjml.
When importing a template where e.g. a custom padding is set then those are ignored to.

I've tried to implement this by myself but I'm kind of confused since there's a [global attribute to set the padding of columns](https://github.com/artf/grapesjs-mjml/blob/df40b0c980cf65fe03d6d89b159213167d443635/src/index.js#L40) and the mj-section component has a custom render function.

---

Compare e.g the following mjml in [mjml.io/try-it-live](https://mjml.io/try-it-live/BJJs6ObVw) and grapes-mjml
```mjml
<mjml>
  <mj-body>
    <mj-section>
      <mj-column background-color="red" padding="100px">
        <mj-text font-size="20px">Hello World</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by josfh2005** [comment]
I have a problem with some mj-column the border/background-color are changed in the canvas and with other this changes are not reflected, but if I generate the final HTML to preview it, theme I see the borders/background-color.

**Comment by m-e-conroy** [comment]
I've been having the same problem with padding being reset.

**Comment by mumumilk** [comment]
@m-e-conroy 

I had the same problem with padding being reseted to defaults (changes persisted on canvas but not on style manager).

padding was beign reseted because the padding property was being added with `detached: true` in https://github.com/artf/grapesjs-mjml/blob/df40b0c980cf65fe03d6d89b159213167d443635/src/style.js#L22

so what i did was to "override" the padding style property with my own parameters:

```js
editor.on('load', () => {
        editor.StyleManager.removeProperty('dimension', 'padding');
        editor.StyleManager.addProperty('dimension', {
          property: 'padding',
          type: 'composite',
          properties: [
            { name: 'Top', property: 'padding-top', type: 'integer', units: ['px', '%', 'em'] },
            { name: 'Right', property: 'padding-right', type: 'integer', units: ['px', '%', 'em'] },
            { name: 'Bottom', property: 'padding-bottom', type: 'integer', units: ['px', '%', 'em'] },
            { name: 'Left', property: 'padding-left', type: 'integer', units: ['px', '%', 'em'] },
          ],
        });
})
```

another solution as well is to prevent style manager reset by setting `resetStyleManager: false` in mjml `pluginOpts` (keep in mind that you'll have to provide your own property and sectors config)

```js
pluginsOpts = {
  ['grapesjs-mjml']: {
    resetStyleManager: false,
  },
},
```

hope this helps anyone with the same problem

**Comment by DRoet** [comment]
I wouldn't be opposed to removing `detached: true` in a PR if it causes more problems then it solves but it would require more testing

**Comment by skbhagat40** [comment]
I am also facing the same issue, 
I have added option to change column padding in `Column.js`
`stylable: [
          "padding",
          "padding-top",
          "padding-left",
          "padding-right",
          "padding-bottom",
         ...
]`
When I change padding, the background color gets changed, but If I copy the html , the changes are getting reflected there.

**Comment by skbhagat40** [comment]
for temporary fix, I have added following code inside, model `updated method`
```
updated(property, value, previousValue) {
        console.log({ property, value, previousValue });
        if (value["padding-right"]) {
          this.getEl().style.paddingRight = value["padding-right"];
        }
        if (value["padding-left"]) {
          this.getEl().style.paddingLeft = value["padding-left"];
        }
        if (value["padding-top"]) {
          this.getEl().style.paddingTop = value["padding-top"];
        }
        if (value["padding-bottom"]) {
          this.getEl().style.paddingBottom = value["padding-bottom"];
        }
        const placeholders = this.components().models.filter(
          (model) => model.attributes.tagName === "mj-placeholder"
        );
        // console.log({value});
        value.length &&
          value.length != placeholders.length &&
          placeholders.forEach((p) => p.remove());
```

**Comment by yanfanvip** [comment]
update renderStyle method, this can work.
but It's not the best way
`
renderStyle() {
        let model_style = this.model.get('style') || {}
        const style = Object.keys(this.model.get('style')).map(attr=>`${attr}:${model_style[attr]};`)
        this.el.setAttribute('style', `${style.join(' ')} ${this.el.getAttribute('style')}`);
},
`

**Comment by gustavohleal** [comment]
> update renderStyle method, this can work. but It's not the best way
> 
> ```
> renderStyle() {
>         const model_style = this.model.get('style') || {}
>         const style = Object.keys(this.model.get('style')).map(attr=>`${attr}:${model_style[attr]};`)
>         this.el.setAttribute('style', `${style.join(' ')} ${this.el.getAttribute('style')}`);
> },
> ```

Sorry for my lack of knowledge, but where exactly that should go? Along with the initialization of the editor or should I change directly in the grapes?

**Comment by ronaldohoch** [comment]
> > update renderStyle method, this can work. but It's not the best way
> > ```
> > renderStyle() {
> >         const model_style = this.model.get('style') || {}
> >         const style = Object.keys(this.model.get('style')).map(attr=>`${attr}:${model_style[attr]};`)
> >         this.el.setAttribute('style', `${style.join(' ')} ${this.el.getAttribute('style')}`);
> > },
> > ```
> 
> Sorry for my lack of knowledge, but where exactly that should go? Along with the initialization of the editor or should I change directly in the grapes?

Hello there, found here:

https://github.com/artf/grapesjs-mjml/blob/master/src/components/Column.js#L83

**Comment by yanfanvip** [comment]
> 更新 renderStyle 方法，这可以工作。 但这不是最好的方法
> 
> ```
> renderStyle() {
>         const model_style = this.model.get('style') || {}
>         const style = Object.keys(this.model.get('style')).map(attr=>`${attr}:${model_style[attr]};`)
>         this.el.setAttribute('style', `${style.join(' ')} ${this.el.getAttribute('style')}`);
> },
> ```

update 

```
renderStyle() {
        const model_style = this.model.get('style') || {}
        const style = Object.keys(this.model.get('style')).map(attr=>`${attr}:${model_style[attr]};`)
        this.el.setAttribute('style', `${style.join(' ')} ${this.el.getAttribute('style')} ${this.attributes.style}`);
},
```

just add ${this.attributes.style}

**Comment by ronaldohoch** [comment]
> > 更新 renderStyle 方法，这可以工作。 但这不是最好的方法
> > ```
> > renderStyle() {
> >         const model_style = this.model.get('style') || {}
> >         const style = Object.keys(this.model.get('style')).map(attr=>`${attr}:${model_style[attr]};`)
> >         this.el.setAttribute('style', `${style.join(' ')} ${this.el.getAttribute('style')}`);
> > },
> > ```
> 
> update
> 
> ```
> renderStyle() {
>         const model_style = this.model.get('style') || {}
>         const style = Object.keys(this.model.get('style')).map(attr=>`${attr}:${model_style[attr]};`)
>         this.el.setAttribute('style', `${style.join(' ')} ${this.el.getAttribute('style')} ${this.attributes.style}`);
> },
> ```
> 
> just add ${this.attributes.style}

Thank for that, but just a little correction.:
`this.el.setAttribute('style', `${this.attributes.style} ${style.join(' ')} ${this.el.getAttribute('style')}`);`

At the last line, put the `${this.attributes.style}` at start of the string, if you put it at the end it won't update the padding through the style editor. It won't overwrite the padding set in the columnPadding option

**Comment by ronaldohoch** [comment]
Hello again.
Guys, find other bug, here is the solution:

```js
            renderStyle() {
                const model_style = this.model.get('style') || {}
                const stylable = this.model.attributes.stylable;
                const style = Object.keys(model_style).filter(attr=>stylable.indexOf(attr)>0).map(attr => `${attr}:${model_style[attr]};`);
                this.el.setAttribute('style', `${this.attributes.style} ${style.join(' ')} ${this.el.getAttribute('style')}`);              
            },
```

**What is the problem i find?**
Any other attribute, like css-class and id are turning into style. Part of that issue i describe there:
https://github.com/artf/grapesjs/discussions/4022

**So, i update the style variable line from this:**
`const style = Object.keys(this.model.get('style')).map(attr => `${attr}:${model_style[attr]};`)`
into this:
```js
   const stylable = this.model.attributes.stylable;
   const style = Object.keys(model_style).filter(attr=>stylable.indexOf(attr)>0).map(attr => `${attr}:${model_style[attr]};`);
```

**Explanation:**
Here i'm using the property stylable from the component's model to filter what will turn into style.

**Comment by artf** [comment]
Should be fixed in the latest release https://github.com/GrapesJS/mjml/releases/tag/v1.0.5
