### ISSUE TITLE
Question: Social Media Group - Facebook Component

### ISSUE THREAD

**Issue by HeyWrecker** [GrapesJS/mjml#238]
Hello,

Is the Facebook social media component intended to be used to provide a Facebook link to a business or organizations Facebook page or is it exclusively designed to share something specific to your timeline? It appears to be the latter, even though that seems counter-intuitive to me since many emails simply provide links to the social media accounts in the headers and footers. I'd just like some confirmation on how it is intended to work and if there are any workarounds or plans to change this behavior if it is indeed functioning as designed.

Best,
Rick

**Comment by HeyWrecker** [comment]
Hi all, just a quick bump to see if anyone knows why the behavior differs from the other Social Icon components and if this differing behavior is expected or a bug?

**Comment by HeyWrecker** [comment]
One additional note- the Instragram option does take one to the linked IG profile page as opposed to sharing something to your story or feed. This seems contrary to the current Facebook behavior. For an end user, their is no indication that the `href` attribute won't be used as the actual destination which is a cause of confusion for our users.

**Comment by rcloss** [comment]
It's an MJML thing, mj-social-element has a "Share" url instead, if you change it from facebook to facebook-noshare it will just be a standard link instead

https://mjml.io/documentation/#mj-social

**Comment by HeyWrecker** [comment]
@rcloss Sorry for the delayed response. I referenced the documentation, however, in version `0.16.22` of the GrapesJS MJML plugin, that did not appear to be a dropdown option in the visual editor for the social element. Has this been added to a later version? Or does this need to be done in the code view?

**Comment by rcloss** [comment]
you'd have to update the Trait to have a differerent list of options

There might be a better way to do it, but on the component:add I'm loooking to see if it's mj-social-element and then doing this:

`		a.getTrait('name').set('options', [
			{value: "", name: "Custom"},
			{value: "dribbble-noshare", name: "Dribbble"},
			{value: "facebook-noshare", name: "Facebook"},
			{value: "facebook", name: "Facebook - Sharing"},
			{value: "instagram-noshare", name: "Instagram"},
			{value: "linkedin-noshare", name: "Linkedin"},
			{value: "linkedin", name: "Linkedin - Sharing"},
			{value: "medium-noshare", name: "Medium"},
			{value: "pinterest-noshare", name: "Pinterest"},
			{value: "pinterest", name: "Pinterest - Sharing"},
			{value: "snapchat-noshare", name: "Snapchat"},
			{value: "tumblr-noshare", name: "Tumblr"},
			{value: "tumblr", name: "Tumblr - Sharing"},
			{value: "twitter-noshare", name: "Twitter"},
			{value: "twitter", name: "Twitter - Sharing"},
			{value: "vimeo-noshare", name: "Vimeo"},
			{value: "website-noshare", name: "Website"},
			{value: "xing-noshare", name: "Xing"},
			{value: "xing", name: "Xing - Sharing"},
			{value: "youtube-noshare", name: "Youtube"}
			
		])`

**Comment by HeyWrecker** [comment]
Got it, thanks!
