### ISSUE TITLE
Issue with 2 Columns width and inline style

### ISSUE THREAD

**Issue by franckBML** [GrapesJS/mjml#257]
Hello,

I think there is an issue with inline style when using multiple columns (at least 2 colums, didn't try other options).
The class "mj-column-per-50" is used and working. But the inline style is still set to width=100%. 
```
<div class="mj-column-per-50 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
>
```
I have the issue with Outlook where my 2 columns take 100% width, rather than 50%,. It seems Outlook is only using inline styles and not CSS. While everything is fine on gmail.

**Comment by ErgoleJeT** [comment]
Hello, i have the same problem : is there a planned date for the correction ?
