### ISSUE TITLE
Making modifications without refreshing the page ?

### ISSUE THREAD

**Issue by TomAtTeam** [GrapesJS/mjml#265]
Hi everyone,

I have a question about GrapesJS with MJML.

When I go on this page : https://grapesjs.com/demo-mjml.html,

Let’s say I’d like to change the color of the title « My Company » and make it red.

![Capture d’écran (223)](https://user-images.githubusercontent.com/94383921/141810447-caece4d8-54f7-4737-b78c-8c4e711ae612.png)

It’s working fine, the title turns to red.

![Capture d’écran (224)](https://user-images.githubusercontent.com/94383921/141810460-affe3f21-1718-4cc1-b033-ee0e7bf8a67d.png)

But then if I want to put « My Company » in bold it doesn’t work. If I wan’t to make it work I have to refresh the page and then to put it in bold.

![Capture d’écran (225)](https://user-images.githubusercontent.com/94383921/141810472-503b8082-1172-4d33-976c-a0a1b4fda07e.png)

Does someone have an idea to make it work without refresh the page please and without using the style manager ?

Thank you !

Thomas

**Comment by Bran72** [comment]
I'm facing this issue too, but it's when I drag a custom block 'mj-column' or 'mj-group'...
Did you find any solution ? Thx !

**Comment by TomAtTeam** [comment]
Hi ! Unfortunately I didn't find the solution to my problem, so I can't help you on this right now... Sorry !
Thomas

**Comment by Bran72** [comment]
No problem, if it could help I got this solution.
I put a listener (here when I drag a specific block), and I 'refresh' the canvas by loading the current data:
```
this.Editor.on('block:drag:stop', (block, component) => {
   if (component.id === 'mycustomcomponent-id') {
      const data = this.Editor.storeData()
      this.Editor.DomComponents.clear()
      this.Editor.loadData(data)
   }
})
```

**Comment by TomAtTeam** [comment]
> No problem, if it could help I got this solution. I put a listener (here when I drag a specific block), and I 'refresh' the canvas by loading the current data:
> 
> ```
> this.Editor.on('block:drag:stop', (block, component) => {
>    if (component.id === 'mycustomcomponent-id') {
>       const data = this.Editor.storeData()
>       this.Editor.DomComponents.clear()
>       this.Editor.loadData(data)
>    }
> })
> ```

Thank you very much for your help ! It worked for me ! 

Have a nice day !

Thomas

**Comment by artf** [comment]
Shouldn't be an issue anymore
