### ISSUE TITLE
Is mj-attributes broken in grapesjs?

### ISSUE THREAD

**Issue by TechBill** [GrapesJS/mjml#269]
mj-attributes seems having no effect to the layout of mjml. I had to apply attribute to each components. 

Using the "try it now" over at mjml, the mj-attributes is working as intended.

**Comment by apuntovanini** [comment]
I confirm this! (or maybe we both make the same mistake)

**Comment by apuntovanini** [comment]
It seems tags for mjml-attributes are not properly closed

```
<mj-attributes>
  <mj-all padding="5px" />
  <mj-button background-color="red" />
</mj-attributes>
```

seems to convert into

```
<mj-attributes>
  <mj-all padding="5px"><mj-button background-color="red"></mj-button></mj-all>
</mj-attributes>
```

**Comment by ronaldohoch** [comment]
Are you guys using `mj-attributes` inside `mj-head` as shown in documentation?
https://documentation.mjml.io/#mj-attributes

**Comment by apuntovanini** [comment]
Yes, it's inside <mj-head>

**Comment by beatwiz** [comment]
Still happening on latest versions.

In mjml.io "try it live" this works with direct effect on the content:

```
    <mj-attributes>
      <mj-all padding="100" />
      <mj-text color="#000" font-size="26px" line-height="1.3" />
    </mj-attributes>
```

While on GrapeJS, this has no effect:

```
    <mj-attributes>
      <mj-all padding="100" />
      <mj-text color="#000" font-size="26px" line-height="1.3" />
    </mj-attributes>
```

And gets converted during import to:

```
    <mj-attributes>
      <mj-all padding="100">
        <mj-text color="#000" font-size="26px" line-height="1.3">
        </mj-text>
      </mj-all>
    </mj-attributes>
```

Thanks in advance!

**Comment by RakulAgn** [comment]
The MJ-ATTRIBUTES supported in grapesjs-mjml ? i just try to implement a global style concept for that if the mj-attributes and mj-class is there it could be usefull

**Comment by DiegoGonzalezCruz** [comment]
Hello everybody, did anybody find how to bypass this limitation? 
I am having the same issue.

**Comment by artf** [comment]
`mj-attributes` is not broken, it's simply not supported.

Please check the README for supported MJML components and in case you want it supported, PRs are welcome.
