### ISSUE TITLE
onRender method is not called

### ISSUE THREAD

**Issue by Brewal** [GrapesJS/mjml#273]
Unless I'm missing something, as the `render()` method is overrided in all mjml components, the fact that the `postRender()` method is not called there never triggers the `onRender()` method documented in grapesjs. 

The only way I can execute code there is to copy the entire render method in the components I want to update. Is this intended ?

**Comment by ErgoleJeT** [comment]
Hello, any news about that ? How can i do to separate the view from the model on a custom component ? The goal is to show a placeholder distinct from the model.
