### ISSUE TITLE
Listen Import Event, dont work editor.on('run:mjml-import:change'

### ISSUE THREAD

**Issue by karlitaviky811** [GrapesJS/mjml#316]
Hi, I'm using the latest version of grapesjsmjml and this solution doesn't work for me. I need to listen to the event when importing, can someone help me?

try this solution, but it doesn't work https://github.com/GrapesJS/mjml/issues/104

**Comment by lechuhuuha** [comment]
Hi 
Have you tried to look at the doc in this link
https://grapesjs.com/docs/api/commands.html#commands

Maybe its like this

```
editor.on('stop:mjml-import:before', (mjml) => {
  console.log(mjml);
})
```

**Comment by karlitaviky811** [comment]
También estoy intentando usar  this.editor.runCommand('mjml-get-code').html para obtener el html generado, pero tampoco me funciona. Por favor me ayudarías a saber como tener acceso al html y css ?.

**Comment by karlitaviky811** [comment]
I'm also trying to use this.editor.runCommand('mjml-get-code').html to get the generated html, but it doesn't work for me either. Please help me to know how to access html and css ?

**Comment by karlitaviky811** [comment]
try the proposed solution, but it is not importing the mjml code. I need to listen to the event and have access to the mjml code I'm loading.


And here for another functionality I need to access the generated html
  to store it in the data base, but using this.editor.runCommand('mjml-get-code').html doesn't work for me

**Comment by karlitaviky811** [comment]
I also have this problem, please help me to know how I can solve it ? error_ core.mjs:7739 ERROR Error: Malformed MJML. Check that your structure is correct and enclosed in <mjml> tags.
[
![Captura de pantalla de 2023-02-15 10-56-34](https://user-images.githubusercontent.com/41756264/219063686-578e4833-2f8d-48bf-af17-061c59c37f54.png)
](url)

the wrapper is not generating well the code initially <mjml>...<mjml>

**Comment by lechuhuuha** [comment]
> I also have this problem, please help me to know how I can solve it ? error_ core.mjs:7739 ERROR Error: Malformed MJML. Check that your structure is correct and enclosed in tags. [ ![Captura de pantalla de 2023-02-15 10-56-34](https://user-images.githubusercontent.com/41756264/219063686-578e4833-2f8d-48bf-af17-061c59c37f54.png) ](url)
> 
> the wrapper is not generating well the code initially ...

the mjml you have is not enclose in mjml tag
Its need to be like this 

```mjml
<mjml>
  <mj-body>

     // the rest of your code in image

  </mj-body>
</mjml>
```

**Comment by karlitaviky811** [comment]
however, this is the code that is generated by drag and drop (just dragging to create the plant) :/. How can it initialize? because installing the library and making editor.init should generate it automatically.

**Comment by karlitaviky811** [comment]
however, this is the code that is generated by drag and drop (just dragging to create the plant) :/. How can it initialize? because installing the library and making editor.init should generate it automatically.

**Comment by karlitaviky811** [comment]
however, this is the code that is generated by drag and drop (just dragging to create the plant) :/. How can it initialize? because installing the library and making editor.init should generate it automatically.

**Comment by karlitaviky811** [comment]
however, this is the code that is generated by drag and drop (just dragging to create the plant) :/. How can it initialize? because installing the library and making editor.init should generate it automatically.

**Comment by karlitaviky811** [comment]
however, this is the code that is generated by drag and drop (just dragging to create the plant) :/. How can it initialize? because installing the library and making editor.init should generate it automatically.

**Comment by karlitaviky811** [comment]
If I want to create a plant by drag and drop (from the beginning) I am not building the code correctly so it is sold without the initial tags

**Comment by karlitaviky811** [comment]
If I want to create a plant by drag and drop (from the beginning) I am not building the code correctly so it is sold without the initial tags

**Comment by lechuhuuha** [comment]
> If I want to create a plant by drag and drop (from the beginning) I am not building the code correctly so it is sold without the initial tags

sorry but i dont really understand what you said and this issue getting a little drag out. You can contact me from telegram for further assistance https://t.me/huuhazozo.

**Comment by karlitaviky811** [comment]
If I want to create a plant by drag and drop (from the beginning) I am not building the code correctly so it is sold without the initial tags
