### ISSUE TITLE
Cannot find namespace 'grapesjs.Plugin' in grapejs-mjml index.d.ts

### ISSUE THREAD

**Issue by zeskysee** [GrapesJS/mjml#325]
When npm install grapesjs 0.21.1 with grapesjs-mjml 1.0.4 in angular get the following error:

````
Error: node_modules/grapesjs-mjml/dist/index.d.ts:99:23 - error TS2503: Cannot find namespace 'grapesjs'.

99 declare const plugin: grapesjs.Plugin<PluginOptions>;
                         ~~~~~~~~
````

To reproduce the issue, you check out the following repository:
[https://github.com/zeskysee/angular-grapejs-mjml-issue](https://github.com/zeskysee/angular-grapejs-mjml-issue)

**Comment by artf** [comment]
Fixed here https://github.com/GrapesJS/mjml/releases/tag/v1.0.5
