### ISSUE TITLE
mj-navbar and CKEditor

### ISSUE THREAD

**Issue by pepoteloko** [GrapesJS/mjml#327]
Hello,

I use grapesjs-mjml and grapesjs-plugin-ckeditor, and I discover than I cannot edit the text of the the navbar-links.
I disable CKEditor and now I can edit the link text.
I try it on the demo page and the same is happening: https://grapesjs.com/demo-mjml.html

The console says:
Error: The specified element mode is not supported on element: "a". I understand that is saying: "CKeditor do not works on links".

It's a bug? Or it's a feature? 😄 There is any workaround?

**Comment by artf** [comment]
Yes, you have to enable the editing of `a` via CKEditor

**Comment by pepoteloko** [comment]
I try to enable the editing of `a`, but i goes wierd. When I change styles, change URL, any change in the sidebar, text gets duplicated. If my link is Hello, and I change color, padding and font-size, I got HelloHelloHelloHello 🤣

**Comment by artf** [comment]
@pepoteloko the latest version fixes it
