### ISSUE TITLE
Default width is not working properly in current version

### ISSUE THREAD

**Issue by RakulAgn** [GrapesJS/mjml#328]
![image](https://github.com/GrapesJS/mjml/assets/119593989/8a3b48b0-92be-4d9f-bedc-79597042417d)

**Comment by artf** [comment]
Default width is working properly in current version...

**Comment by RakulAgn** [comment]
The Current Version Package is Used on the Above Example ? it is checked yesterday and till now its seems like that !

**Comment by RakulAgn** [comment]
![image](https://github.com/GrapesJS/mjml/assets/119593989/462fe9de-7ef9-4bf9-bfc3-da5ec50534e3)

But Kindly Look into Traits the Full width is not even enabled i am right ?
