### ISSUE TITLE
BUG : Navbar link render twice when paste text into in the demo link

### ISSUE THREAD

**Issue by lechuhuuha** [GrapesJS/mjml#329]
Hi when i copy and paste the text to the navbar link 
its split the navbar link into 2

Here is the video

https://github.com/GrapesJS/mjml/assets/59781669/adf5328e-decc-40da-ac5f-45c69f6abc1c

This can be recreate by using the demo version

and current version of grapesjs mjml

Can you take a look at this  @artf ?

Thanks

**Comment by artf** [comment]
Closing as, after a check, it doesn't seem to be an issue anymore (maybe was related to CKEditor)
