### ISSUE TITLE
Mjml in react,Component cant't draggable

### ISSUE THREAD

**Issue by yongma16** [GrapesJS/mjml#333]
compared to mjml demo，I find a question，react actual render html  content  lack 
`<mjml>
  <mj-body>
    <mj-section>
    </mj-section>
  </mj-body>
</mjml>
`it is render in react page，i think it may cause the component cant not draggle：
`<div id="izqz" data-gjs-type="wrapper" class=""></div>`

wraning info:
`{
    "errors": [
        "Target collection not found",
        "Component not draggable, acceptable by [[data-gjs-type=\"mj-body\"], [data-gjs-type=\"mj-wrapper\"]]"
    ],
    "model": {
        "tagName": "mj-section",
        "type": "mj-section"
    },
    "context": "sorter",
    "level": "warning"
}`

**Comment by DreamCloudProject** [comment]
I have the same issue with Lit Element. This problem can be related because React and Lit are using web-components.

**Comment by yongma16** [comment]
> 

thank you very much，I solved the problem by the grapes addcomponents api

**Comment by DreamCloudProject** [comment]
> > 
> 
> thank you very much，I solved the problem by the grapes addcomponents api

So, what did you exatcly fix? I can't add any blocks to the canvas.

**Comment by DreamCloudProject** [comment]
<img width="875" alt="image" src="https://github.com/GrapesJS/mjml/assets/7961936/adb3a625-0615-4576-a2bb-9c43b3e0d715">
Here's what I see in the console.

**Comment by yongma16** [comment]
> > > 
> > 
> > 
> > thank you very much，I solved the problem by the grapes addcomponents api
> 
> So, what did you exatcly fix? I can't add any blocks to the canvas.
I write a demo，you can Reference code
https://github.com/yongma16/grapes-mjml-react/blob/master/src/views/EmailPage.tsx

**Comment by yongma16** [comment]
> I have the same issue with Lit Element. This problem can be related because React and Lit are using web-components.

Brother, does the MJML plug-in have an api for converting html to mjml?

**Comment by DreamCloudProject** [comment]
> > > > 
> > > 
> > > 
> > > thank you very much，I solved the problem by the grapes addcomponents api
> > 
> > 
> > So, what did you exatcly fix? I can't add any blocks to the canvas.
> > I write a demo，you can Reference code
> > https://github.com/yongma16/grapes-mjml-react/blob/master/src/views/EmailPage.tsx

I have solved a problem. Thanks!

**Comment by DreamCloudProject** [comment]
> > I have the same issue with Lit Element. This problem can be related because React and Lit are using web-components.
> 
> Brother, does the MJML plug-in have an api for converting html to mjml?

No, I store the original mjml code separately in the database. I only request the parsed HTML to be sent in an email. Accordingly, I request the mjml code in the grapesjs editor.

**Comment by artf** [comment]
Closing as it seems to be solved.
