### ISSUE TITLE
Question: How to add the custom action(variable)

### ISSUE THREAD

**Issue by TechWhiz10** [GrapesJS/mjml#337]
Hi, @Artur Arseniev.
Grapesjs is very awesome. just like WordPress or Bubble.

I made a function using https://github.com/GrapesJS/grapesjs/issues/481.
editor.RichTextEditor.add('custom-vars', {
  icon: `<select class="gjs-field">
		<option value="">- Select -</option>
        <option value="[[firstname]]">FirstName</option>
        <option value="[[lastname]]">LastName</option>
        <option value="[[age]]">Age</option>
      </select>`,
    // Bind the 'result' on 'change' listener
  event: 'change',
  result: (rte, action) => rte.insertHTML(action.btn.firstChild.value),
  // Reset the select on change
  update: (rte, action) => { action.btn.firstChild.value = "";}
})

It works well in grapesjs-plugins-newsletter. but it doesn't work in grapesjs-mjml.
Sometimes it works.

![Uploading image.png…]
![error](https://github.com/GrapesJS/mjml/assets/141584727/713f804b-6c68-4d61-8021-a1d35d3c1ca1)
()

I don't know why it doesn't work.
How can I resolve this problem?

**Comment by LcsGa** [comment]
Hi have the exact same issue for the exact same need!

**Comment by LcsGa** [comment]
Did you find a solution @TechWhiz10?

**Comment by TechWhiz10** [comment]
@LcsGa not yet

**Comment by artf** [comment]
Tried it on the current demo and it seems to work as expected.
If you still face the issue please open a proper bug report with reproducible steps and demo.
