### ISSUE TITLE
BUG:  Found a Bug in MJML Image Block

### ISSUE THREAD

**Issue by RakulAgn** [GrapesJS/mjml#339]
### **Description:**
When attempting to set the height and width of an image to "auto" in the Grapesjs MJML Example on the official site, an error is thrown in the Chrome console. Once this error occurs, the image cannot be cloned unless it is completely removed.

**### Steps to Reproduce:**

* Navigate to the Grapesjs MJML Example on the official site.
* Add a section and drop an image into it.
* Open the Chrome Developer Console.
* Set the image's height and width to "auto" by typing the word "auto" in the respective input fields.
* Observe the error in the console: TypeError: Cannot read properties of undefined reading toString
* Attempt to clone the image.

### **Expected Behavior:**
The image's height and width should adjust to "auto" without any errors. Cloning functionality should remain unaffected.

### **Actual Behavior:**
An error is thrown in the console when setting the image's height and width to "auto". Cloning functionality for the image is disabled until the image is completely removed.

**Comment by RakulAgn** [comment]
@artf

**Comment by ronaldohoch** [comment]
Hi @RakulAgn, auto is not a valid value to mj-image, if you remove the width property of mj-image it will be set to 100%.
![image](https://github.com/GrapesJS/mjml/assets/2287371/eaba9296-818b-4658-aa49-876065c55b90)
https://mjml.io/try-it-live/4WyCHcXK1A

**Comment by RakulAgn** [comment]
Yeah thats right but its not handled in grapesjs mjml. in user point of view what if they type auto incase ?

**Comment by ronaldohoch** [comment]
Thanks for finding this.

Here we have a custom build of mjml, so we have solved :D

Also, i've made a PR to it. https://github.com/GrapesJS/mjml/pull/344

**Comment by RakulAgn** [comment]
Thanks dude it took 2 month :(
