### ISSUE TITLE
Question: Does mjml support body component to configure background image?

### ISSUE THREAD

**Issue by yongma16** [GrapesJS/mjml#340]
I want to configure the background image in the body component of the mjml drag-and-drop editor，

Does mjml support body component to configure background image?

https://grapesjs.com/demo-mjml.html

The official website does not have a body configuration image. I want to know why it is set like this. Is it because the background image cannot be added due to email html compatibility?

![image](https://github.com/GrapesJS/mjml/assets/48764359/d13958b0-d447-499d-913e-84ce62be9d2f)

**Comment by artf** [comment]
> Does mjml support body component to configure background image?

No, [it doesn't](https://documentation.mjml.io/#mj-body) and that's why you don't see it there
