### ISSUE TITLE
MJML plugin no longer working

### ISSUE THREAD

**Issue by rogueturnip** [GrapesJS/mjml#342]
Hi!

I'm trying to get the MJML plugin working and it seems that the "Invalid Target Position" bug is popping up.

I'm using GrapesJS 0.21.5 and mjml 1.0.5.

This is using @grapesjs/react as a wrapper and everything works fine once the mjml plugin is removed.

I tested it here https://grapesjs-react-default-ui-etee4r.stackblitz.io

thanks!

**Comment by artf** [comment]
Try to check your dependencies

<img width="327" alt="Screenshot 2024-08-21 at 18 41 53" src="https://github.com/user-attachments/assets/9489c9c5-f343-4761-89d7-35376ef4b045">
