### ISSUE TITLE
Table creation drag and drop issue

### ISSUE THREAD

**Issue by shahjay715** [GrapesJS/mjml#346]
I have created a react application using grapesjs mjml to create templates using drag and drop components , I couldn’t find anything on how to you create tables using drag and drop approach.
I am using grapesjs 0.16 and grapesjs mjml - 0.5.5. Can somebody please guide on how to do it? I have been doing right now is create from word and paste in grapesjs mjml editor in text block. Please suggest

**Comment by artf** [comment]
> I am using grapesjs 0.16 and grapesjs mjml - 0.5.5

Please, first ensure to use the latest versions, then you can open an issue providing all the details
