### ISSUE TITLE
Set HTML with style in component

### ISSUE THREAD

**Issue by Kevin-Vu** [GrapesJS/mjml#347]
I want to update the html of a component.
So I do this : `component.components('<h1 style="text-align-left">TITLE</h1>')`.
But when after I get the content of my component, it doesn't have the style.
`component.toHTML()` returns `<mj-text><h1 id="someId">TITLE</h1></mj-text>`. 

Any idea why ?

**Comment by artf** [comment]
`style="text-align: right"`
