### ISSUE TITLE
Create custom MJML component

### ISSUE THREAD

**Issue by mabonoah** [GrapesJS/mjml#352]
Hello everyone, 

I'm using the following version with an Angular 7 project:
- "grapesjs": "^0.15.10",
- "grapesjs-mjml": "^0.6.0"

I want to create a custom mjml component like mj-text built-in components. 
I have tried multiple ways but they are not working with me and I didn't find enough resources.   

Please any help.

**Comment by adrianodias8** [comment]
Hi there!

I also have been playing with components  and specifically for preview text i can give you my 2 cents from my investigation

here is my ticket:
https://github.com/GrapesJS/mjml/issues/351
(very basic component test that i did)

regarding documentation i recommend you to check components folder to understand the structure https://github.com/GrapesJS/mjml/tree/master/src/components

also check the base component from  base repo here: https://github.com/GrapesJS/grapesjs/blob/dev/src/dom_components/model/Component.ts

 this is just the mjml plugin  
 and read this :
https://grapesjs.com/docs/modules/Components.html (components)
https://grapesjs.com/docs/modules/Traits.html#add-traits-to-components (traits)

I hope this helps and points you in the right direction.

best,
Adriano Dias

**Comment by artf** [comment]
Thanks @adrianodias8
If anybody wants to enhance the documentation on the README file, I'll be happy to merge the PR.
