### ISSUE TITLE
active development

### ISSUE THREAD

**Issue by rogueturnip** [GrapesJS/mjml#354]
Hi, I just noticed this project hasn't been updated since June 2023, almost a year.  Is there still development planned on this or should it be considered abandoned?

**Comment by ndusart** [comment]
@artf what is the status of this project ?

Issues are left unresponded even for issues that were acknowledged to need fixes for several years. :worried:

**Comment by rogueturnip** [comment]
I'm starting to look at using this https://github.com/zalify/easy-email-editor because the grapes version is so out of date.  But this will only work for folks wanting to work in React.

**Comment by lechuhuuha** [comment]
> I'm starting to look at using this https://github.com/zalify/easy-email-editor because the grapes version is so out of date. But this will only work for folks wanting to work in React.

laste time i checked

about 3 months ago

the editor still have some bug in the demo for some basic tasks

**Comment by artf** [comment]
Sorry guys, we're coming back to give more support to this project.
