### ISSUE TITLE
BUG: While Typing Texting and editing text style it showing previous value of the text

### ISSUE THREAD

**Issue by RakulAgn** [GrapesJS/mjml#357]
You can refer the video

https://github.com/GrapesJS/mjml/assets/119593989/d71d98d7-aa82-4ec9-aac8-f3f8a994a21e

Actually Behaviour
When Editing Texting ( Typing Text ) and try to edit the text for example try to change the text font family it will show the previous value of the text

Expected Behaviour
When editing typing text and editing any options it should not change the text value

@artf

**Comment by artf** [comment]
Related to the CKEditor plugin, not the mjml itself.
