### ISSUE TITLE
Bug: While Dropping a Divider inside the column with image property the border is removed for image 

### ISSUE THREAD

**Issue by RakulAgn** [GrapesJS/mjml#359]
https://github.com/GrapesJS/mjml/assets/119593989/d4c1d920-0b58-4a18-b2f2-e21b55dc7611

@artf

**Comment by RakulAgn** [comment]
This Issue Occurs on every where like column and section try to add border for column and section just drop another block inside the before that dropping drag the component to the bordered section or column and drop it the border is removed from the html content but once it reloaded it showing again @artf

**Comment by artf** [comment]
Tried now on the demo and can't reproduce it, I guess something related to the previous core version.
