### ISSUE TITLE
Missing Default Style in HTML Export

### ISSUE THREAD

**Issue by RakulAgn** [GrapesJS/mjml#367]
<img width="1438" alt="Screenshot 2024-08-14 at 7 44 26 AM" src="https://github.com/user-attachments/assets/5d52d31e-916f-4eb5-a1c7-b07a8526531e">

On Canvas it showing 22px but when exported it showing 1px 

@artf

**Comment by danstarns** [comment]
Thank you for raising this, I replicated it here: 

* https://github.com/GrapesJS/mjml/pull/368

A workaround - You can move to any other value like 23px, which will work. 

We will work on a fix soon - contributions are welcome :)

**Comment by RakulAgn** [comment]
Hey Kindly Check this https://github.com/GrapesJS/mjml/pull/369 this is solution it worked for me
