### ISSUE TITLE
bug: editor not compatible with IE11

### ISSUE THREAD

**Issue by punctos** [GrapesJS/mjml#77]
Hi team, 
We decided to use mjml in grapes js. Everything works fine except on **IE11** and **Edge**. Most of our customers are on IE11.
On IE11 we have:
![1](https://user-images.githubusercontent.com/42639471/44519235-c39a2b00-a6cc-11e8-9e05-34e57b679934.png)

![2](https://user-images.githubusercontent.com/42639471/44519242-c8f77580-a6cc-11e8-924d-b2a24889ae79.png)

On Edge we have
![3](https://user-images.githubusercontent.com/42639471/44519249-cd239300-a6cc-11e8-8d73-014e06f9587d.png)

![4](https://user-images.githubusercontent.com/42639471/44519257-ce54c000-a6cc-11e8-882a-2072832bb943.png)

Do you have a chance to correct the problems?
Thank you for your comeback.

**Comment by kickbk** [comment]
This has to do with strict code and those browsers. I started rewriting some of the functions, but to get this completely redone is crazy amount of work. It's not difficult or impossible to fix, just tedious. If you do fix it, please do share your code with the rest of us.

**Comment by tdejong-tools4ever** [comment]
Edge appears to be fixed, still occurs in IE11
